### ISSUE TITLE
fix: fix form validation in GUI (Accept only the correct type)

### ISSUE THREAD

**Issue by lewismcfarlane-sparta** [Patrikturc/EmployeesProjectG1#36]
Search by Hire Date & search by age fields accept strings which return errors in console.

Search by ID: if you put a negative 5 digit number (-52134) it will return 'No employee found matching: -52134'

Search by ID: If you put 6 letter string in field it returns the string. So the issue seems to be if what is in the field is 6 characters it searches it.

Search by age: Inputting 'NaN' breaks it. Null also breaks it. True/false also repeats the same outcome.

**Comment by ChrisRaynerSG** [comment]
fixed for all fields in latest pull request
