### ISSUE TITLE
Data Sanitisation - method to convert DOB strings to YYYY-MM-DD format

### ISSUE THREAD

**Issue by l-hepper** [Patrikturc/EmployeesProjectG1#8]
The date of birth for all employees should be formatted as

Date of Birth (YYYY-MM-DD)

this is not how the dates come in as MM-DD-YYYY

additional note, some dates have leading zeroes and some do not.  e.g. there are some with 04/18/1967 and some with 4/18/1967

This also applies to the Date of Joining field - we should be able to use the same logic to sanitise both.

**Comment by lewismcfarlane-sparta** [comment]
I have since added a formatting method to the DataSanitisation class, which will format the dates correctly.

Need to add implementation of incorrect dates still (incorrect months, dates and years).
